// Code generated by github.com/atombender/go-jsonschema, DO NOT EDIT.

// Copyright (C) 2026 jolyne-nyah. Licensed under GNU GPL v3.
// This program comes with ABSOLUTELY NO WARRANTY.
// See <https://gnu.org> for details.

package config

type ConfigSchemaJson struct {
	// Direct corresponds to the JSON schema field "direct".
	Direct ConfigSchemaJsonDirect `json:"direct,omitempty,omitzero" yaml:"direct,omitempty" mapstructure:"direct,omitempty"`

	// Repos corresponds to the JSON schema field "repos".
	Repos ConfigSchemaJsonRepos `json:"repos,omitempty,omitzero" yaml:"repos,omitempty" mapstructure:"repos,omitempty"`
}

type ConfigSchemaJsonDirect map[string]struct {
	// Dest corresponds to the JSON schema field "dest".
	Dest string `json:"dest" yaml:"dest" mapstructure:"dest"`

	// Outputs corresponds to the JSON schema field "outputs".
	Outputs []string `json:"outputs" yaml:"outputs" mapstructure:"outputs"`
}

type ConfigSchemaJsonRepos map[string]map[string][]string
